Map (num_proc=8): 100%|███████████| 1000/1000 [00:00<00:00, 7850.71 examples/s]
Casting the dataset: 100%|██████| 1000/1000 [00:00<00:00, 155063.18 examples/s]
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at Snowflake/snowflake-arctic-embed-l and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map:   0%|                                      | 0/900 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "/home/edward/Sila/train_edu_bert.py", line 196, in <module>
    main(args)
  File "/home/edward/Sila/train_edu_bert.py", line 109, in main
    dataset = dataset.map(preprocess, batched=True)
  File "/opt/conda/lib/python3.10/site-packages/datasets/dataset_dict.py", line 866, in map
    {
  File "/opt/conda/lib/python3.10/site-packages/datasets/dataset_dict.py", line 867, in <dictcomp>
    k: dataset.map(
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 560, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3035, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3461, in _map_single
    writer.write_batch(batch)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_writer.py", line 563, in write_batch
    arrays.append(pa.array(typed_sequence))
  File "pyarrow/array.pxi", line 248, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 112, in pyarrow.lib._handle_arrow_array_protocol
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_writer.py", line 203, in __arrow_array__
    out = cast_array_to_feature(
  File "/opt/conda/lib/python3.10/site-packages/datasets/table.py", line 1797, in wrapper
    return func(array, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/table.py", line 1995, in cast_array_to_feature
    return feature.cast_storage(array)
  File "/opt/conda/lib/python3.10/site-packages/datasets/features/features.py", line 1126, in cast_storage
    raise ValueError(
ValueError: Class label 5 greater than configured num_classes 5